### ISSUE TITLE
Can't chat with the i.a

### ISSUE THREAD

**Issue by Blakyrin** [qwersyk/Newelle#14]
When trying to use Newelle, i receive "failed to send bot a message"
![image](https://github.com/qwersyk/Newelle/assets/111029746/62524225-6ef6-408a-a889-19d3be1bf6bc)

**Comment by qwersyk** [comment]
Thank you for your comment, this message can appear for three reasons, one - you have no internet connection, two - baichat has changed the code a lot that the past api doesn't work, three - baichat can't respond at the moment, in this case the third option is most likely. We can't do anything about it, because this is the most normal option, we are sorry, but if we for example used openai api, then in a few messages all tokens would be spent.
