### ISSUE TITLE
"Failed to send bot a message"

### ISSUE THREAD

**Issue by pushpixels** [qwersyk/Newelle#38]
Installed with Flatpak and it is not working "Failed to send bot a message"

Am I missing something? Thanks.

**Comment by qwersyk** [comment]
Thank you for your comment, at the moment our programme doesn't work because BaiChat stopped working without registration, the new code already has support for other services, but at the moment there are problems with exporting to Flathub. You can try to run the code in Builder for example, but the code may not be stable, we are sorry. We hope that in the future we will be able to make our programme work, but for now you can use Bavarder.
