### ISSUE TITLE
[BUG TRACKING] Various crashes

### ISSUE THREAD

**Issue by Darkpepito** [qwersyk/Newelle#7]
Hello,  
I just discovered this app as a flatpak and it is awesome !  
But unfortunately, the app just crah when I type certain prompts. For example :  
`list all files in /home/darkpepito` result in a crash.  
I use i3 as my main WM but I don't know if it's important.
  
Here are the specs of my machine :  
Dell Latitude-E5470
CPU: Intel cored i5-6300U
GPU: Intel HD graphics 520
16 GB of RAM
OS: Zorin OS 16.2  

Thank you for your time !

**Comment by qwersyk** [comment]
Thank you, we're glad you enjoyed our app, and thank you for reporting the bug. If you can tell us more about the crashes, the program always crashes during these actions, can provide possible screenshots of chat, and can run the program through the terminal to get the error message (running the command `flatpak run io.github.qwersyk.Newelle`), the program is very crude and many crashes that I am trying to fix, but can not get the exact cause, because when I test the error happens and not. And once again, thank you very much about the bug report, I will try as much as possible in future versions to fix the error.

**Comment by Darkpepito** [comment]
Ok I will investigate on my side in the coming days, do you want from me to open new issues each time the crash's cause is different or I just put them in this one ?

**Comment by qwersyk** [comment]
Thank you very much, you can put them in this one.

**Comment by Darkpepito** [comment]
So, when entering the `list files in /home/darkpepito`, it returns me this :  
```
(newelle:2): Gtk-CRITICAL **: 13:32:01.054: gtk_text_attributes_ref: assertion 'values != NULL' failed
**
Gtk:ERROR:../gtk/gtktextlayout.c:1261:set_para_values: code should not be reached
Bail out! Gtk:ERROR:../gtk/gtktextlayout.c:1261:set_para_values: code should not be reached
```

So it seems to be a GTK error, but I have absolutely zero experience with it.

**Comment by qwersyk** [comment]
Thank you very much, I will try to remove this error in future versions.

**Comment by kumraa-1** [comment]
I really like the concept of your app but nearly every command that interacts with the system leads to a crash.
I'm running on Fedora 38 and installed the app via Flatpak.

Here's a few excamples:
`create an empty file in my home folder`
(newelle:2): Gtk-CRITICAL **: 08:32:48.124: gtk_text_attributes_ref: assertion 'values != NULL' failed
(newelle:2): Pango-CRITICAL **: 08:32:48.147: pango_tab_array_new: assertion 'initial_size >= 0' failed

`Find out my MAC address`
(newelle:2): Gtk-CRITICAL **: 08:36:20.603: gtk_text_attributes_ref: assertion 'values != NULL' failed

(newelle:2): Gtk-CRITICAL **: 08:36:20.603: gtk_text_attributes_ref: assertion 'values != NULL' failed

`do ls -l of my home folder` worked perfectly
follow up command `also include the hidden files`
(newelle:2): Gtk-CRITICAL **: 08:39:07.646: gtk_text_attributes_ref: assertion 'values != NULL' failed
**
Gtk:ERROR:../gtk/gtktextlayout.c:1261:set_para_values: code should not be reached
Bail out! Gtk:ERROR:../gtk/gtktextlayout.c:1261:set_para_values: code should not be reached

**Comment by qwersyk** [comment]
Thank you for your feedback. We're sorry to hear about such failures, we're trying to understand and fix what the problem is, but at the moment I don't know enough about GTK code to understand what the problem is, our code runs on high-level python and this error occurs on lower-level code, I hope more experts will be able to understand what the error is, but thank you very much for your bug report and the error itself.

**Comment by Darkpepito** [comment]
If I don't say shit, GTK is the thing to make graphical apps ? If so, had you try to make a command line version ? Or a Qt one ?

**Comment by kumraa-1** [comment]
> 

I'm wondering on how and what distro you tested the app for funcionality? I mean this hinders basic functionality.
